In [1]:
import scipy.io
import pandas as pd

In [138]:
mat_data = scipy.io.loadmat('final_tiles/PatientData/p11/post_10percent/tiles_p11post.mat')

In [139]:
mat_data.keys()

dict_keys(['__header__', '__version__', '__globals__', 'None', 'Tumor_newgrid_trimmed', 'CD8prolif_newgrid_trimmed', 'CD8nonprolif_newgrid_trimmed', 'finaltiles', 'Tum_dense_gridstack', 'Tum_prolif_gridstack', 'CD8_nonprolif_gridstack', 'CD8_prolif_gridstack', 'prolifTumGrid', 'CD8prolifGrid', 'CD8nonprolifGrid', '__function_workspace__'])

In [100]:
# mat_data.items()

In [48]:
# for structs
column1 = mat_data['Lnorm_obs_post'].ravel()
column2 = mat_data['Lnorm_obs_pre'].ravel()
column3= mat_data['n_CD8_observed_PRE_all'].ravel()
column4 = mat_data['n_CD8_observed_all'].ravel()

In [140]:
# for tiles
column1 = mat_data['Tumor_newgrid_trimmed'].ravel()
column2 = mat_data['CD8prolif_newgrid_trimmed'].ravel()
column3 = mat_data['CD8nonprolif_newgrid_trimmed'].ravel()
column4 = mat_data['finaltiles'].ravel()
column5 = mat_data['Tum_dense_gridstack'].ravel()
column6 = mat_data['Tum_prolif_gridstack'].ravel()
column7 = mat_data['CD8_nonprolif_gridstack'].ravel()
column8 = mat_data['CD8_prolif_gridstack'].ravel()
column9 = mat_data['prolifTumGrid'].ravel()
column10 = mat_data['CD8prolifGrid'].ravel()
column11 = mat_data['CD8nonprolifGrid'].ravel()

In [136]:
column = mat_data['allSystems'].ravel()
data = {'allSystems': column}

In [49]:
# for structs
data = {
    'Lnorm_obs_post': column1,
    'Lnorm_obs_pre': column2,
    'n_CD8_observed_PRE_all': column3,
    'n_CD8_observed_all': column4,
}

In [143]:
#print length of column of the set column1, column2, column3,etc.
print(len(column1))
print(len(column2))
print(len(column3))
print(len(column4))
print(len(column5))
print(len(column6))
print(len(column7))
print(len(column8))
print(len(column9))
print(len(column10))
print(len(column11))

890
96
4300
1926821
80000
80000
80000
80000
902253
902253
902253

In [144]:
# for tiles
data = {
    # 'finaltiles': column4,
    'prolifTumGrid': column9,
    'CD8prolifGrid': column10,
    'CD8nonprolifGrid': column11,
}

In [145]:
df = pd.DataFrame(data)

In [147]:
df.head()

   prolifTumGrid  CD8prolifGrid  CD8nonprolifGrid
0              0              0                 0
1              0              0                 0
2              0              0                 0
3              0              0                 0
4              0              0                 0

In [149]:
df.to_csv('final_tiles/PatientData/p11/post_10percent/tiles_p11post_grid.csv')

In [150]:
data2 = {
    'Tum_dense_gridstack': column5,
    'Tum_prolif_gridstack': column6,
    'CD8_nonprolif_gridstack': column7,
    'CD8_prolif_gridstack': column8,
}

In [151]:
df2 = pd.DataFrame(data2)

In [152]:
df2.head()

,Tum_dense_gridstack,Tum_prolif_gridstack,CD8_nonprolif_gridstack,CD8_prolif_gridstack
0,0,0,0,0
1,0,0,0,0
2,0,0,0,0
3,0,0,0,0
4,0,0,0,0

In [129]:
df2.to_csv('final_tiles/PatientData/p11/post_10percent/tiles_p11post_gridstack.csv')

In [137]:
df3 = pd.DataFrame(data)
df3.to_csv('final_tiles/PatientData/p11/post_10percent/structs_p11post.csv')